apiVersion: v2
appVersion: 1.42.0
description: Bridges events and allows you to control your Zigbee devices via MQTT
home: https://github.com/Koenkk/zigbee2mqtt
icon: https://www.zigbee2mqtt.io/logo.png
keywords:
- zigbee
- mqtt
- home-assistant
kubeVersion: '>=1.26.0-0'
maintainers:
- name: Koen Kanters
name: zigbee2mqtt
sources:
- https://github.com/Koenkk/zigbee2mqtt
version: 1.42.0
