apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    log_dest stdout
    allow_anonymous false
    listener 1883
    listener 9001
    protocol websockets
    persistence true
    password_file /mosquitto/password/password.txt
    persistence_file mosquitto.db
    persistence_location /mosquitto/data/
