apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    {{- range .Values.service }}
    - name: {{ .name }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      port: {{ .containerPort }}
    {{- end }}
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
  externalIPs:
    - "192.168.0.4"
